author:
  name: Elliot
  email: elliot.a.richards@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.01741310069337487
color:
  saturation: 0.829753
  brandStrength: 1
  lightness: 0.9350161
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0
layout_spectrum: 0.1734694
name: i eat robots
