author:
  name: Elliot
  email: elliot.a.richards@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.017413100693374872
color:
  saturation: 0.1247131316922605
  brandStrength: 0.1254203710705042
  lightness: 0.18292687041684985
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.573128059040755
layout_spectrum: 0.7927382125053555
name: i eat robots
